<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\HugoMatters.Core\HugoMatters.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Packs\hugo-profile.json" />
  </ItemGroup>

</Project>
